name: format

on:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: DoozyX/clang-format-lint-action@v0.14
        with:
          source: "."
          extensions: "h,cpp,c,hpp"
          clangFormatVersion: 14
